// These public pages validate credentials client-side before using the FastAPI auth endpoints.
import { zodResolver } from "@hookform/resolvers/zod";
import { Leaf, LoaderCircle } from "lucide-react";
import { useForm } from "react-hook-form";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { z } from "zod";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import { errorMessage } from "../services/api";

const loginSchema = z.object({ email: z.string().email("Enter a valid email"), password: z.string().min(1, "Password is required"), remember: z.boolean() });
const registerSchema = z.object({ fullName: z.string().min(2, "Enter your name"), email: z.string().email("Enter a valid email"), password: z.string().min(8, "Use at least 8 characters") });
function AuthFrame({ children }: { children: React.ReactNode }) { return <main className="grid min-h-screen place-items-center bg-[radial-gradient(ellipse_at_top,#134e4a_0%,#0b1120_45%)] p-4"><section className="w-full max-w-md rounded-2xl border border-slate-700/70 bg-slate-950/80 p-7 shadow-2xl"><div className="mb-8 flex items-center gap-3 text-xl font-bold"><span className="rounded-xl bg-teal-500 p-2 text-slate-950"><Leaf /></span>TerraScore</div>{children}</section></main>; }
export function LoginPage({ forgot = false }: { forgot?: boolean }) { const { user, login } = useAuth(); const navigate = useNavigate(); const toast = useToast(); const form = useForm<z.infer<typeof loginSchema>>({ resolver: zodResolver(loginSchema), defaultValues: { remember: true } }); if (user) return <Navigate to="/dashboard" replace />; if (forgot) return <AuthFrame><h1 className="text-2xl font-bold">Reset password</h1><p className="mt-2 text-sm text-slate-400">Password reset is UI-ready. The current backend does not expose a reset-password endpoint.</p><Link className="btn-primary mt-6" to="/login">Back to sign in</Link></AuthFrame>; const submit = form.handleSubmit(async (values) => { try { await login(values.email, values.password, values.remember); navigate("/dashboard"); } catch (error) { toast.show(errorMessage(error), "error"); } }); return <AuthFrame><h1 className="text-2xl font-bold">Welcome back</h1><p className="mt-1 text-sm text-slate-400">Sign in to monitor your farms.</p><form className="mt-6 space-y-4" onSubmit={submit}><label className="block"><span className="label">Email</span><input className="field" autoComplete="email" {...form.register("email")} />{form.formState.errors.email && <small className="text-red-400">{form.formState.errors.email.message}</small>}</label><label className="block"><span className="label">Password</span><input type="password" className="field" autoComplete="current-password" {...form.register("password")} />{form.formState.errors.password && <small className="text-red-400">{form.formState.errors.password.message}</small>}</label><div className="flex items-center justify-between text-sm"><label className="flex gap-2 text-slate-400"><input type="checkbox" {...form.register("remember")} />Remember me</label><Link className="text-teal-400" to="/forgot-password">Forgot password?</Link></div><button disabled={form.formState.isSubmitting} className="btn-primary w-full">{form.formState.isSubmitting && <LoaderCircle className="animate-spin" size={16} />}Sign in</button></form><p className="mt-6 text-center text-sm text-slate-400">New to TerraScore? <Link className="text-teal-400" to="/register">Create an account</Link></p></AuthFrame>; }
export function RegisterPage() { const { user, register } = useAuth(); const navigate = useNavigate(); const toast = useToast(); const form = useForm<z.infer<typeof registerSchema>>({ resolver: zodResolver(registerSchema) }); if (user) return <Navigate to="/dashboard" replace />; const submit = form.handleSubmit(async (values) => { try { await register(values.fullName, values.email, values.password); navigate("/dashboard"); } catch (error) { toast.show(errorMessage(error), "error"); } }); return <AuthFrame><h1 className="text-2xl font-bold">Create account</h1><p className="mt-1 text-sm text-slate-400">Start intelligent agricultural credit monitoring.</p><form className="mt-6 space-y-4" onSubmit={submit}>{([ ["fullName", "Full name", "text"], ["email", "Email", "email"], ["password", "Password", "password"] ] as const).map(([name, label, type]) => <label key={name} className="block"><span className="label">{label}</span><input className="field" type={type} autoComplete={name === "password" ? "new-password" : undefined} {...form.register(name)} />{form.formState.errors[name] && <small className="text-red-400">{form.formState.errors[name]?.message}</small>}</label>)}<button disabled={form.formState.isSubmitting} className="btn-primary w-full">{form.formState.isSubmitting && <LoaderCircle className="animate-spin" size={16} />}Create account</button></form><p className="mt-6 text-center text-sm text-slate-400">Already have an account? <Link className="text-teal-400" to="/login">Sign in</Link></p></AuthFrame>; }
export function ResetPasswordPage() { return <AuthFrame><h1 className="text-2xl font-bold">Choose a new password</h1><p className="mt-2 text-sm text-slate-400">This screen is ready for the reset-token workflow. The current FastAPI backend does not expose a password-reset endpoint, so no password is sent or simulated.</p><Link className="btn-primary mt-6" to="/login">Back to sign in</Link></AuthFrame>; }
