// These operational pages expose training, analytics, reports, profile, and settings that the backend supports.
import { useMutation, useQuery } from "@tanstack/react-query";
import { Download, FileUp, LoaderCircle, Play, Save, UserCircle } from "lucide-react";
import { useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, Empty, Loading } from "../components/ui";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import { errorMessage } from "../services/api";
import { dataApi, predictionApi } from "../services/terrascore";
export function TrainingPage() { const toast = useToast(); const [values, setValues] = useState({ lat: 28.4, lon: 77, start_date: "2023-01-01", end_date: "2023-12-31" }); const train = useMutation({ mutationFn: dataApi.train, onSuccess: (data) => toast.show(data.status), onError: (error) => toast.show(errorMessage(error), "error") }); return <div className="max-w-2xl space-y-7"><div><h1 className="page-title">Model training</h1><p className="mt-1 text-slate-400">Queues the existing XGBoost training pipeline in the FastAPI background worker.</p></div><Card className="p-6"><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); train.mutate(values); }}>{([ ["lat", "Latitude", "number"], ["lon", "Longitude", "number"], ["start_date", "Start date", "date"], ["end_date", "End date", "date"] ] as const).map(([key, label, type]) => <label key={key}><span className="label">{label}</span><input className="field" type={type} step="any" value={values[key]} onChange={(event) => setValues({ ...values, [key]: type === "number" ? Number(event.target.value) : event.target.value })}/></label>)}<button className="btn-primary sm:col-span-2" disabled={train.isPending}>{train.isPending ? <LoaderCircle className="animate-spin" size={16}/> : <Play size={16}/>}Start training</button></form>{train.data && <div className="mt-5 rounded-lg bg-teal-500/10 p-4 text-sm text-teal-200">{train.data.status}. Refresh server logs or training history once the worker completes.</div>}<p className="mt-4 text-xs text-slate-500">Accuracy, precision, recall, F1, ROC-AUC, and confusion matrices are not supplied by the current backend contract, so this UI does not invent them.</p></Card></div>; }
export function AnalyticsPage() { const analytics = useQuery({ queryKey: ["analytics"], queryFn: dataApi.analytics }); if (analytics.isLoading) return <Loading label="Loading analytics" />; return <div className="space-y-7"><div><h1 className="page-title">Analytics</h1><p className="mt-1 text-slate-400">Daily trends generated from your stored predictions.</p></div><Card className="p-6"><h2 className="font-semibold">Monthly prediction volume</h2><div className="mt-6 h-80">{analytics.data?.prediction_trends.length ? <ResponsiveContainer><BarChart data={analytics.data.prediction_trends}><CartesianGrid stroke="#1e293b" vertical={false}/><XAxis dataKey="date" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155" }}/><Bar dataKey="predictions" fill="#2dd4bf" radius={[6, 6, 0, 0]}/></BarChart></ResponsiveContainer> : <Empty>No analytics available yet.</Empty>}</div></Card></div>; }
export function ReportsPage() { const toast = useToast(); const predictions = useQuery({ queryKey: ["predictions"], queryFn: predictionApi.list }); const [file, setFile] = useState<File | null>(null); const upload = useMutation({ mutationFn: predictionApi.upload, onSuccess: (blob) => { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "terrascore-predictions.csv"; anchor.click(); URL.revokeObjectURL(url); toast.show("Batch prediction CSV downloaded."); }, onError: (error) => toast.show(errorMessage(error), "error") }); return <div className="space-y-7"><div><h1 className="page-title">Reports</h1><p className="mt-1 text-slate-400">Download server-generated prediction PDFs or process batch prediction files.</p></div><div className="grid gap-5 lg:grid-cols-2"><Card className="p-6"><h2 className="font-semibold">Prediction reports</h2><div className="mt-4 space-y-2">{predictions.data?.length ? predictions.data.map((prediction) => <div key={prediction.id} className="flex items-center justify-between rounded-lg bg-slate-950 p-3 text-sm"><span>{prediction.prediction_date} · Score {prediction.credit_score}</span><button className="btn-secondary px-3 py-1.5" onClick={() => window.open(predictionApi.reportUrl(prediction.id), "_blank", "noopener") }><Download size={15}/>PDF</button></div>) : <Empty>No prediction reports available.</Empty>}</div></Card><Card className="p-6"><h2 className="font-semibold">Batch prediction upload</h2><p className="mt-2 text-sm text-slate-400">CSV/XLSX must contain latitude, longitude, start_date, and end_date.</p><input className="field mt-5" type="file" accept=".csv,.xlsx" onChange={(event) => setFile(event.target.files?.[0] ?? null)}/><button className="btn-primary mt-4" disabled={!file || upload.isPending} onClick={() => file && upload.mutate(file)}>{upload.isPending ? <LoaderCircle className="animate-spin" size={16}/> : <FileUp size={16}/>}Upload and download results</button></Card></div></div>; }
export function ProfilePage() { const { user } = useAuth(); return <div className="max-w-2xl space-y-7"><div><h1 className="page-title">Profile</h1><p className="mt-1 text-slate-400">Your authenticated TerraScore account.</p></div><Card className="flex items-center gap-5 p-6"><div className="grid h-16 w-16 place-items-center rounded-full bg-teal-500 text-2xl font-bold text-slate-950">{user?.full_name?.[0] ?? user?.email[0]?.toUpperCase()}</div><div><h2 className="text-xl font-semibold">{user?.full_name ?? "TerraScore user"}</h2><p className="text-slate-400">{user?.email}</p><p className="mt-2 text-xs text-slate-500">Member since {user ? new Date(user.created_at).toLocaleDateString() : "—"}</p></div></Card><Card className="p-6"><h2 className="font-semibold">Account management</h2><p className="mt-2 text-sm text-slate-400">Profile editing, password changes, and profile-image upload are ready for UI integration once the backend exposes corresponding authenticated endpoints.</p></Card></div>; }
export function SettingsPage() { const [dark, setDark] = useState(true); const [notifications, setNotifications] = useState(true); return <div className="max-w-2xl space-y-7"><div><h1 className="page-title">Settings</h1><p className="mt-1 text-slate-400">Local display preferences. They do not modify backend configuration.</p></div><Card className="divide-y divide-slate-800 p-2">{[["Dark interface", dark, setDark], ["Browser notifications", notifications, setNotifications]].map(([label, checked, setChecked]) => <label key={label as string} className="flex cursor-pointer items-center justify-between p-4"><span>{label as string}</span><input type="checkbox" checked={checked as boolean} onChange={(event) => (setChecked as (value: boolean) => void)(event.target.checked)} /></label>)}</Card></div>; }
export function NotFoundPage() { return <main className="grid min-h-screen place-items-center bg-slate-950 p-5 text-center"><div><p className="text-7xl font-bold text-teal-400">404</p><h1 className="mt-3 text-2xl font-bold">Page not found</h1><a className="btn-primary mt-6" href="/">Return to dashboard</a></div></main>; }
